// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int reps = Integer.parseInt(args[0]);
		int greater = 0;
		int less = 0;

		for(int i = 0; i < reps; i++){

			double num = Math.random();
			if(num > 0.5){
				greater++;
			} else{
				less++;
			}

		}

		System.out.println("> 0.5:  " + greater + " times");
		System.out.println("<= 0.5:  " + less + " times" );
		
		double ratio = 0;
		if(less > 0){
			ratio = (double) greater/less;
			System.out.println("Ratio: " + ratio);
		}
	}
}
